---
title: "Jennings Invertrbrate Community"
author: "Colleen Cosgrove"
date: "4 October 2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r combine datasets}
#Combine the four individual CSVs from each sample date
#Note to self: never do in a new tab what you can do in a new column...

#smartbind in gtools can combine datasets
library(gtools)

##Load invert community files and merge them into one csv file.
date4=read.csv("C:/Users/Colleen/Dropbox/Jennings Invertebrates/beerbottles_10.15.16.csv")
date4[is.na(date4)]<-0
date4=date4[c(1:93),c(1:129)]
date3=read.csv("C:/Users/Colleen/Dropbox/Jennings Invertebrates/beerbottles_8.10.16.csv")
date3[is.na(date3)]<-0
date3=date3[c(1:95),c(1:115)]
date2=read.csv("C:/Users/Colleen/Dropbox/Jennings Invertebrates/beerbottles_5.15.16.csv")
date2[is.na(date2)]<-0
date2=date2[c(1:95),c(1:117)]
date1=read.csv("C:/Users/Colleen/Dropbox/Jennings Invertebrates/beerbottles_10.6.15.csv")
date1[is.na(date1)]<-0
date1=date1[c(1:91),c(1:80)]
colnames(date1)

commdata=smartbind(date1,date2,date3,date4)
write.csv(commdata)

#Once datasets are combined, check to make sure no misspellings in col names
colnames(commdata)

#remove any NAs
is.na(commdata[,1])
#91,186,281,374 = rows with all NA's
commdata=commdata[-c(91,186,281,374),]
commdata[is.na(commdata)]<-0
is.na(commdata)

write.csv(commdata,"invertcommdata2.csv")
```

For the EntSA poster:
1. Totals by ecosystem, data
2. Gamma diversity between ecosystems
3. RDA
4. Can we show diversity by Kriging???


```{r Load data}
#SET UP

#Load Data
commdata=read.csv("C:/Users/Colleen/OneDrive/Documents/School/Research/Data/Inverts/invertcomm/invertcommdata.csv", header=T)
treedata=read.csv("C:/Users/Colleen/Dropbox/Jennings 2016/New Adult Basal Area.csv")
soildata=read.csv("C:/Users/Colleen/OneDrive/Documents/School/Grad School/SpatialStats/soil data May 08 for tree plots.csv")
treedata[is.na(treedata)] <- 0
treedata=treedata[treedata$ecosys!="S",] #Remove the stream plots -- Will need to put these back in when I fix the commdata$ecosystem columns.

library(vegan)
library(packfor)
dim(commdata)
```

```{r Explatory Stats}
#General summation and graph by date
sum(commdata$Total) #Total=99517 individuals
plot(commdata$Total~commdata$Date) #Most individuals in falls
dateordered=ordered(commdata$Date, levels = c("10.6.15","5.5.16","8.10.16","10.15.16"))
sumplot=boxplot(commdata$Total~dateordered, xlab="Date", ylab="Average Site Sum")
sumplot2=boxplot(commdata$Total~dateordered, xlab="Date", ylab="Average Site Sum", ylim=c(0,1000))

ecoplot=plot(commdata$Total~commdata$Habitat, xlab="Ecosystem", ylab="Average Ecosystem Sum")
ecoplot2=plot(commdata$Total~commdata$Habitat, xlab="Ecosystem", ylab="Average Ecosystem Sum", ylim=c(0,1000))

#abundance by date and ecosystem
abund=aov(commdata$Total~commdata$Habitat*commdata$Date)
summary(abund)
plot(abund)
shapiro.test(commdata$Total)
#shapiro.test is super non-normal; log transform best transforms the datam but not great..
sqtot=lm(commdata$Total)
abund1=aov(sqtot~commdata$Habitat*commdata$Date)
summary(abund1)
plot(abund1)
shapiro.test(sqtot)
TukeyHSD(abund1)
```

```{r Diversity}
#Gamma diversity between ecosystems
H=diversity(commdata, index="shannon")

gammadiv=with(commdata, tapply(specnumber(commdata),Habitat, mean))
````

```{r RDA}
#RDA analysis
dim(commdata)
colnames(commdata)
rdadate1=commdata[commdata$Date=="10.15.16",]
tree.hel.soil=merge(rdadate1,soildata)
dim(tree.hel.soil)
rownames(tree.hel.soil)=tree.hel.soil[,1]
tree.hel.soil=na.exclude(tree.hel.soil)
# Here is the global analysis. Can proceed  Use adj. R square as additional stopping criterion.
colnames(tree.hel.soil)
hel.rda.fulsoil = rda(tree.hel.soil[,5:155], tree.hel.soil[,165:189])
anova(hel.rda.fulsoil)
RsquareAdj(hel.rda.fulsoil)
global.thresh=RsquareAdj(hel.rda.fulsoil)$adj.r.squared
# Here is the forward selection command and then constructing a model with selected variables.
hel.rda.for=forward.sel(tree.hel.soil[,10:42], tree.hel.soil[,52:76], adjR2thresh=global.thresh)
hel.rda.for
names(tree.hel.soil)
hel.rda.selsoil = rda(tree.hel.soil[,10:42] ~ as.matrix(tree.hel.soil[,c(52,54,56,57,58)]))
anova(hel.rda.selsoil)
RsquareAdj(hel.rda.selsoil)
plot(hel.rda.selsoil)
````
When comparing invertebrate community to soil variables:
Date 1 (10.6.15): insignificant. p=0.305
Date 2 (5.5.16): insignificant. p=0.943
Date 3 (8.10.16): insignificant. p=0.402
Date 4 (10.16.15): insiginificant. p=0.115

When comparing invertebrate community to tree community:

