---
title: "pitfall invert stats"
author: "Colleen"
date: "1/7/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load data}
pitfall=read.csv("C:/Users/crc31/dropbox/Jennings Invertebrates/Cosgrove pitfall inverts_comb.csv", header=T)
dim(pitfall)
soildat=read.csv("C:/Users/crc31/OneDrive/Documents/School/Grad School/SpatialStats/soil data May 08 for tree plots.csv")
treedata=read.csv("C:/Users/crc31/Dropbox/Jennings 2016/New Adult Basal Area.csv")
#fiddle with the tree data
treedata[is.na(treedata)] <- 0
treedata=treedata[treedata$ecosys!="S",] #Remove the stream plots -- Will need to put these back in when I fix the commdata$ecosystem columns.
tree.ringsum=treedata[1:83,]
for(i in 1:83) {
	tree.ringsum[i,10:42]=treedata[i,10:42]+treedata[i+83,10:42]+treedata[i+166,10:42]  }
rownames(tree.ringsum)=tree.ringsum[,1]
# Let's look at a rank abbundance plot for fun
tree.colsums=apply(tree.ringsum[,10:42],2,sum)
plot(rank(tree.colsums),tree.colsums, xlab="tree species")

# Perform Hellinger transformation on tree species data so that RDA is based on Hellinger distance
tree.rowsums=apply(tree.ringsum[,10:42],1,sum)
tree.hel=tree.ringsum
tree.hel[,10:42]=tree.hel[,10:42]/tree.rowsums
tree.hel[,10:42]=sqrt(tree.hel[,10:42])

#change NAs in the count columns to 0s.
pitfall[is.na(pitfall)]<-0

##the column "kick" is designed to remove rows that are mis-labeled or duplicate samples. e.g., like 3 Q1 from the same date. Let's remove those.
pitfall=subset(pitfall, kick=="no")

##lets add in the data for soil, which will also add in the habitat type information.
names(pitfall)[names(pitfall)=='ï..Site']<-'Plot'
pitfall=merge(pitfall, soildat, by="Plot")
pitfall=merge(pitfall,tree.hel, by="Plot")

###Subset data
date1=pitfall[pitfall$Sample.pd=="Date 1",]
date2=pitfall[pitfall$Sample.pd=="Date 2",]
date3=pitfall[pitfall$Sample.pd=="Date 3",]
date4=pitfall[pitfall$Sample.pd=="Date 4",]

#load libraries
library(vegan)
```

Decoupling Stats - Community-wide
```{r RDA Date 1}
#remove NAs.
date1=na.omit(date1)
#save a back-up for later, just in case.
date1.2=date1
##rda by soil
hel.rda.fulsoil = rda(date1[,5:205], date1[,229:253])
anova(hel.rda.fulsoil)#AYO
RsquareAdj(hel.rda.fulsoil)
global.thresh=RsquareAdj(hel.rda.fulsoil)$adj.r.squared

##Pitfall inverts by trees
hel.rda.fulsoil = rda(date1[,5:205],date1[,c(263:297)])
anova(hel.rda.fulsoil)
RsquareAdj(hel.rda.fulsoil)
global.thresh=RsquareAdj(hel.rda.fulsoil)$adj.r.squared

##Pitfall inverts by PCNM
colnames(date1)
all.geog.dist=vegdist(date1[,211:212],method="euclid")
all.pcnm1=pcnm(all.geog.dist)
all.pcnmvecs=all.pcnm1$vectors
# If you can get the PCNM library to run, you could do the line below to select only significantly structured PCNMs
#tree.hel.all.pcnm=cbind(date1,all.pcnmvecs[,which(all.pcnm1$Moran_I[,2]<0.05)])
tree.hel.all.pcnm=cbind(date1,all.pcnmvecs)
names(tree.hel.all.pcnm)
# Now run step 1, global analysis
hel.rda.all.fulpcnm=rda(tree.hel.all.pcnm[,5:205], tree.hel.all.pcnm[,299:314])
anova(hel.rda.all.fulpcnm)
RsquareAdj(hel.rda.all.fulpcnm)
global.thresh=RsquareAdj(hel.rda.all.fulpcnm)$adj.r.squared
## Variance partitioning not needed because no significance.

##INVERTS BY ECOSYSTEM
hel.rda.fulsoil = rda(date1[,5:205]~date1$TerrType)
anova(hel.rda.fulsoil)
RsquareAdj(hel.rda.fulsoil)
global.thresh=RsquareAdj(hel.rda.fulsoil)$adj.r.squared


####CORE PLOTS####
date1=date1.2[date1.2$EP.x=="Core",]
##rda by soil
hel.rda.fulsoil = rda(date1[,5:205], date1[,229:253])
anova(hel.rda.fulsoil)
RsquareAdj(hel.rda.fulsoil)
global.thresh=RsquareAdj(hel.rda.fulsoil)$adj.r.squared

###Pitter patter, let's get atter. Let's do that sweet sweet forward selection
##Forward selection
hel.rda.fulsoil.none = rda(date1[,5:205]~1)
hel.rda.fulsoil = rda(date1[,5:205], date1[,229:253])

hel.rda.fulsoil.full=rda(date1[,5:205]~date1$Ptot_long+date1$Po_long+date1$pH_long+date1$moist_long+date1$ps1_long+date1$ps2_long+date1$percc_long+date1$cton_long+date1$Ptot_nug+date1$Po_nug+date1$pH_nug+date1$moist_nug+date1$ps1_nug+date1$ps2_nug+date1$percc_nug+date1$pomc_nug+date1$cton_nug+date1$Ptot_short+date1$Po_short+date1$pH_short+date1$moist_short+date1$ps1_short+date1$percc_short+date1$pomc_short+date1$cton_short)

tree.sel=ordiR2step(hel.rda.fulsoil.none,scope=formula(hel.rda.fulsoil.full),Pin=0.05,R2scope=TRUE)
tree.sel

##Just the variables forward selected
hel.rda.fulsoil = rda(date1[,5:205], date1[,c(239,248)])
anova(hel.rda.fulsoil)
RsquareAdj(hel.rda.fulsoil)
global.thresh=RsquareAdj(hel.rda.fulsoil)$adj.r.squared

##Pitfall inverts by trees
hel.rda.fulsoil = rda(date1[,5:205],date1[,c(263:297)])
anova(hel.rda.fulsoil)
RsquareAdj(hel.rda.fulsoil)
global.thresh=RsquareAdj(hel.rda.fulsoil)$adj.r.squared

##Pitfall inverts by PCNM
colnames(date1)
all.geog.dist=vegdist(date1[,211:212],method="euclid")
all.pcnm1=pcnm(all.geog.dist)
all.pcnmvecs=all.pcnm1$vectors
# If you can get the PCNM library to run, you could do the line below to select only significantly structured PCNMs
#tree.hel.all.pcnm=cbind(date1,all.pcnmvecs[,which(all.pcnm1$Moran_I[,2]<0.05)])
tree.hel.all.pcnm=cbind(date1,all.pcnmvecs)
names(tree.hel.all.pcnm)
# Now run step 1, global analysis
hel.rda.all.fulpcnm=rda(tree.hel.all.pcnm[,5:205], tree.hel.all.pcnm[,299:306])
anova(hel.rda.all.fulpcnm)
RsquareAdj(hel.rda.all.fulpcnm)
global.thresh=RsquareAdj(hel.rda.all.fulpcnm)$adj.r.squared

## no variance partitioning needed because no significance/soil effect.

##INVERTS BY ECOSYSTEM
hel.rda.fulsoil = rda(date1[,5:205]~date1$TerrType)
anova(hel.rda.fulsoil)
RsquareAdj(hel.rda.fulsoil)
global.thresh=RsquareAdj(hel.rda.fulsoil)$adj.r.squared

####CORE+EDGE####
date1=date1.2[date1.2$EP.x!="Trans",]
##rda by soil
hel.rda.fulsoil = rda(date1[,5:205], date1[,229:253])
anova(hel.rda.fulsoil)
RsquareAdj(hel.rda.fulsoil)
global.thresh=RsquareAdj(hel.rda.fulsoil)$adj.r.squared

###Pitter patter, let's get atter. Let's do that sweet sweet forward selection
##Forward selection
hel.rda.fulsoil.none = rda(date1[,5:205]~1)
hel.rda.fulsoil = rda(date1[,5:205], date1[,229:253])

hel.rda.fulsoil.full=rda(date1[,5:205]~date1$Ptot_long+date1$Po_long+date1$pH_long+date1$moist_long+date1$ps1_long+date1$ps2_long+date1$percc_long+date1$cton_long+date1$Ptot_nug+date1$Po_nug+date1$pH_nug+date1$moist_nug+date1$ps1_nug+date1$ps2_nug+date1$percc_nug+date1$pomc_nug+date1$cton_nug+date1$Ptot_short+date1$Po_short+date1$pH_short+date1$moist_short+date1$ps1_short+date1$percc_short+date1$pomc_short+date1$cton_short)

tree.sel=ordiR2step(hel.rda.fulsoil.none,scope=formula(hel.rda.fulsoil.full),Pin=0.05,R2scope=TRUE)
tree.sel

##Just the variables forward selected
hel.rda.fulsoil = rda(date1[,5:205], date1[,c(249,240)])
anova(hel.rda.fulsoil)
RsquareAdj(hel.rda.fulsoil)
global.thresh=RsquareAdj(hel.rda.fulsoil)$adj.r.squared

##Pitfall inverts by trees
hel.rda.fulsoil = rda(date1[,5:205],date1[,c(263:297)])
anova(hel.rda.fulsoil)
RsquareAdj(hel.rda.fulsoil)
global.thresh=RsquareAdj(hel.rda.fulsoil)$adj.r.squared

##Pitfall inverts by PCNM
colnames(date1)
all.geog.dist=vegdist(date1[,211:212],method="euclid")
all.pcnm1=pcnm(all.geog.dist)
all.pcnmvecs=all.pcnm1$vectors
# If you can get the PCNM library to run, you could do the line below to select only significantly structured PCNMs
#tree.hel.all.pcnm=cbind(date1,all.pcnmvecs[,which(all.pcnm1$Moran_I[,2]<0.05)])
tree.hel.all.pcnm=cbind(date1,all.pcnmvecs)
names(tree.hel.all.pcnm)
# Now run step 1, global analysis
hel.rda.all.fulpcnm=rda(tree.hel.all.pcnm[,5:205], tree.hel.all.pcnm[,299:314])
anova(hel.rda.all.fulpcnm)
RsquareAdj(hel.rda.all.fulpcnm)
global.thresh=RsquareAdj(hel.rda.all.fulpcnm)$adj.r.squared

## Variance partitioning - Not needed because there's no pcnm effect

##INVERTS BY ECOSYSTEM
hel.rda.fulsoil = rda(date1[,5:205]~date1$TerrType)
anova(hel.rda.fulsoil)
RsquareAdj(hel.rda.fulsoil)
global.thresh=RsquareAdj(hel.rda.fulsoil)$adj.r.squared
```
```{r RDA Date 2}
#remove NAs.
date2=na.omit(date2)
#save a back-up for later, just in case.
date2.2=date2
##rda by soil
hel.rda.fulsoil = rda(date2[,5:205], date2[,229:253])
anova(hel.rda.fulsoil)
RsquareAdj(hel.rda.fulsoil)
global.thresh=RsquareAdj(hel.rda.fulsoil)$adj.r.squared

##Pitfall inverts by trees
hel.rda.fulsoil = rda(date2[,5:205],date2[,c(263:297)])
anova(hel.rda.fulsoil)
RsquareAdj(hel.rda.fulsoil)
global.thresh=RsquareAdj(hel.rda.fulsoil)$adj.r.squared

##Pitfall inverts by PCNM
colnames(date2)
all.geog.dist=vegdist(date2[,211:212],method="euclid")
all.pcnm1=pcnm(all.geog.dist)
all.pcnmvecs=all.pcnm1$vectors
# If you can get the PCNM library to run, you could do the line below to select only significantly structured PCNMs
#tree.hel.all.pcnm=cbind(date2,all.pcnmvecs[,which(all.pcnm1$Moran_I[,2]<0.05)])
tree.hel.all.pcnm=cbind(date2,all.pcnmvecs)
names(tree.hel.all.pcnm)
# Now run step 1, global analysis
hel.rda.all.fulpcnm=rda(tree.hel.all.pcnm[,5:205], tree.hel.all.pcnm[,299:317])
anova(hel.rda.all.fulpcnm)
RsquareAdj(hel.rda.all.fulpcnm)
global.thresh=RsquareAdj(hel.rda.all.fulpcnm)$adj.r.squared
#### Will do variance partitioning after I figure out what I'm doing with the tree data b/c it's combined plots and not half plots.####

##INVERTS BY ECOSYSTEM
hel.rda.fulsoil = rda(date2[,5:205]~date2$TerrType)
anova(hel.rda.fulsoil)
RsquareAdj(hel.rda.fulsoil)
global.thresh=RsquareAdj(hel.rda.fulsoil)$adj.r.squared

####CORE PLOTS####
date2=date2.2[date2.2$EP.x=="Core",]
##rda by soil
hel.rda.fulsoil = rda(date2[,5:205], date2[,229:253])
anova(hel.rda.fulsoil)
RsquareAdj(hel.rda.fulsoil)
global.thresh=RsquareAdj(hel.rda.fulsoil)$adj.r.squared

###Pitter patter, let's get atter. Let's do that sweet sweet forward selection
##Forward selection
hel.rda.fulsoil.none = rda(date2[,5:205]~1)
hel.rda.fulsoil = rda(date2[,5:205], date2[,229:253])

hel.rda.fulsoil.full=rda(date2[,5:205]~date2$Ptot_long+date2$Po_long+date2$pH_long+date2$moist_long+date2$ps1_long+date2$ps2_long+date2$percc_long+date2$cton_long+date2$Ptot_nug+date2$Po_nug+date2$pH_nug+date2$moist_nug+date2$ps1_nug+date2$ps2_nug+date2$percc_nug+date2$pomc_nug+date2$cton_nug+date2$Ptot_short+date2$Po_short+date2$pH_short+date2$moist_short+date2$ps1_short+date2$percc_short+date2$pomc_short+date2$cton_short)

tree.sel=ordiR2step(hel.rda.fulsoil.none,scope=formula(hel.rda.fulsoil.full),Pin=0.05,R2scope=TRUE)
tree.sel

##Just the variables forward selected
hel.rda.fulsoil = rda(date2[,5:205], date2[,c(246,253)])
anova(hel.rda.fulsoil)
RsquareAdj(hel.rda.fulsoil)
global.thresh=RsquareAdj(hel.rda.fulsoil)$adj.r.squared

##Pitfall inverts by trees
hel.rda.fulsoil = rda(date2[,5:205],date2[,c(263:297)])
anova(hel.rda.fulsoil)
RsquareAdj(hel.rda.fulsoil)
global.thresh=RsquareAdj(hel.rda.fulsoil)$adj.r.squared

##Pitfall inverts by PCNM
colnames(date2)
all.geog.dist=vegdist(date2[,211:212],method="euclid")
all.pcnm1=pcnm(all.geog.dist)
all.pcnmvecs=all.pcnm1$vectors
# If you can get the PCNM library to run, you could do the line below to select only significantly structured PCNMs
#tree.hel.all.pcnm=cbind(date2,all.pcnmvecs[,which(all.pcnm1$Moran_I[,2]<0.05)])
tree.hel.all.pcnm=cbind(date2,all.pcnmvecs)
names(tree.hel.all.pcnm)
# Now run step 1, global analysis
hel.rda.all.fulpcnm=rda(tree.hel.all.pcnm[,5:205], tree.hel.all.pcnm[,299:308])
anova(hel.rda.all.fulpcnm)
RsquareAdj(hel.rda.all.fulpcnm)
global.thresh=RsquareAdj(hel.rda.all.fulpcnm)$adj.r.squared

#forward selection for our PCNM variables
hel.rda.all.pcnm.none=rda(tree.hel.all.pcnm[,5:205]~1)
hel.rda.all.fulpcnm=rda(tree.hel.all.pcnm[,5:205], tree.hel.all.pcnm[,255:284])

hel.rda.all.pcnm.full=rda(tree.hel.all.pcnm[,5:205]~tree.hel.all.pcnm$PCNM1+tree.hel.all.pcnm$PCNM2+tree.hel.all.pcnm$PCNM3+tree.hel.all.pcnm$PCNM4+tree.hel.all.pcnm$PCNM5+tree.hel.all.pcnm$PCNM6+tree.hel.all.pcnm$PCNM7+tree.hel.all.pcnm$PCNM8+tree.hel.all.pcnm$PCNM9+tree.hel.all.pcnm$PCNM10+tree.hel.all.pcnm$PCNM11+tree.hel.all.pcnm$PCNM12+tree.hel.all.pcnm$PCNM13+tree.hel.all.pcnm$PCNM14+tree.hel.all.pcnm$PCNM15+tree.hel.all.pcnm$PCNM16+tree.hel.all.pcnm$PCNM17+tree.hel.all.pcnm$PCNM18+tree.hel.all.pcnm$PCNM19+tree.hel.all.pcnm$PCNM20+tree.hel.all.pcnm$PCNM21+tree.hel.all.pcnm$PCNM22+tree.hel.all.pcnm$PCNM23+tree.hel.all.pcnm$PCNM24+tree.hel.all.pcnm$PCNM25+tree.hel.all.pcnm$PCNM26+tree.hel.all.pcnm$PCNM27+tree.hel.all.pcnm$PCNM28+tree.hel.all.pcnm$PCNM29+tree.hel.all.pcnm$PCNM30)

tree.sel=ordiR2step(hel.rda.all.pcnm.none,scope=formula(hel.rda.all.pcnm.full),Pin=0.05,R2scope=TRUE)
tree.sel

##Just the variables forward selected
hel.rda.all.fulpcnm=rda(tree.hel.all.pcnm[,5:205], tree.hel.all.pcnm[,c(258,255,272,259,276)])
anova(hel.rda.all.fulpcnm)
RsquareAdj(hel.rda.all.fulpcnm)
global.thresh=RsquareAdj(hel.rda.all.fulpcnm)$adj.r.squared

## Variance partitioning
varpart(tree.hel.all.pcnm[,5:205], tree.hel.all.pcnm[,c(246,253)], tree.hel.all.pcnm[,c(258,255,272,259,276)])
## Check to see if it's significant when PCNM and soil come first.
hel.rda.all.partpcnm=rda(tree.hel.all.pcnm[,5:205], tree.hel.all.pcnm[,c(258,255,272,259,276)], tree.hel.all.pcnm[,c(246,253)])
anova(hel.rda.all.partpcnm)
# Yes.
hel.rda.all.partsoil=rda(tree.hel.all.pcnm[,5:205], tree.hel.all.pcnm[,c(246,253)], tree.hel.all.pcnm[,c(258,255,272,259,276)])
anova(hel.rda.all.partsoil)
# Yes.

##INVERTS BY ECOSYSTEM
hel.rda.fulsoil = rda(date2[,5:205]~date2$TerrType)
anova(hel.rda.fulsoil)
RsquareAdj(hel.rda.fulsoil)
global.thresh=RsquareAdj(hel.rda.fulsoil)$adj.r.squared


####CORE+EDGE####
date2=date2.2[date2.2$EP.x!="Trans",]
##rda by soil
hel.rda.fulsoil = rda(date2[,5:205], date2[,229:253])
anova(hel.rda.fulsoil)
RsquareAdj(hel.rda.fulsoil)
global.thresh=RsquareAdj(hel.rda.fulsoil)$adj.r.squared

###Pitter patter, let's get atter. Let's do that sweet sweet forward selection
##Forward selection
hel.rda.fulsoil.none = rda(date2[,5:205]~1)
hel.rda.fulsoil = rda(date2[,5:205], date2[,229:253])

hel.rda.fulsoil.full=rda(date2[,5:205]~date2$Ptot_long+date2$Po_long+date2$pH_long+date2$moist_long+date2$ps1_long+date2$ps2_long+date2$percc_long+date2$cton_long+date2$Ptot_nug+date2$Po_nug+date2$pH_nug+date2$moist_nug+date2$ps1_nug+date2$ps2_nug+date2$percc_nug+date2$pomc_nug+date2$cton_nug+date2$Ptot_short+date2$Po_short+date2$pH_short+date2$moist_short+date2$ps1_short+date2$percc_short+date2$pomc_short+date2$cton_short)

tree.sel=ordiR2step(hel.rda.fulsoil.none,scope=formula(hel.rda.fulsoil.full),Pin=0.05,R2scope=TRUE)
tree.sel

##Just the variables forward selected
hel.rda.fulsoil = rda(date2[,5:205], date2[,c(239,249,230)])
anova(hel.rda.fulsoil)
RsquareAdj(hel.rda.fulsoil)
global.thresh=RsquareAdj(hel.rda.fulsoil)$adj.r.squared

##Pitfall inverts by trees
hel.rda.fulsoil = rda(date2[,5:205],date2[,c(263:297)])
anova(hel.rda.fulsoil)
RsquareAdj(hel.rda.fulsoil)
global.thresh=RsquareAdj(hel.rda.fulsoil)$adj.r.squared

##Pitfall inverts by PCNM
colnames(date2)
all.geog.dist=vegdist(date2[,211:212],method="euclid")
all.pcnm1=pcnm(all.geog.dist)
all.pcnmvecs=all.pcnm1$vectors
# If you can get the PCNM library to run, you could do the line below to select only significantly structured PCNMs
#tree.hel.all.pcnm=cbind(date2,all.pcnmvecs[,which(all.pcnm1$Moran_I[,2]<0.05)])
tree.hel.all.pcnm=cbind(date2,all.pcnmvecs)
names(tree.hel.all.pcnm)
# Now run step 1, global analysis
hel.rda.all.fulpcnm=rda(tree.hel.all.pcnm[,5:205], tree.hel.all.pcnm[,299:315])
anova(hel.rda.all.fulpcnm)
RsquareAdj(hel.rda.all.fulpcnm)
global.thresh=RsquareAdj(hel.rda.all.fulpcnm)$adj.r.squared

## Variance partitioning - Not needed becausse no soil/pcnm effects.

##INVERTS BY ECOSYSTEM
hel.rda.fulsoil = rda(date2[,5:205]~date2$TerrType)
anova(hel.rda.fulsoil)
RsquareAdj(hel.rda.fulsoil)
global.thresh=RsquareAdj(hel.rda.fulsoil)$adj.r.squared
```
```{r RDA Date 3}
#remove NAs.
date3=na.omit(date3)
#save a back-up for later, just in case.
date3.2=date3
##rda by soil
hel.rda.fulsoil = rda(date3[,5:205], date3[,229:253])
anova(hel.rda.fulsoil)#AYO
RsquareAdj(hel.rda.fulsoil)
global.thresh=RsquareAdj(hel.rda.fulsoil)$adj.r.squared

###Pitter patter, let's get atter. Let's do that sweet sweet forward selection
##Forward selection
hel.rda.fulsoil.none = rda(date3[,5:205]~1)
hel.rda.fulsoil = rda(date3[,5:205], date3[,229:253])

hel.rda.fulsoil.full=rda(date3[,5:205]~date3$Ptot_long+date3$Po_long+date3$pH_long+date3$moist_long+date3$ps1_long+date3$ps2_long+date3$percc_long+date3$cton_long+date3$Ptot_nug+date3$Po_nug+date3$pH_nug+date3$moist_nug+date3$ps1_nug+date3$ps2_nug+date3$percc_nug+date3$pomc_nug+date3$cton_nug+date3$Ptot_short+date3$Po_short+date3$pH_short+date3$moist_short+date3$ps1_short+date3$percc_short+date3$pomc_short+date3$cton_short)

tree.sel=ordiR2step(hel.rda.fulsoil.none,scope=formula(hel.rda.fulsoil.full),Pin=0.05,R2scope=TRUE)
tree.sel

##Just the variables forward selected
hel.rda.fulsoil = rda(date3[,5:205], date3[,c(252,238)])
anova(hel.rda.fulsoil)
RsquareAdj(hel.rda.fulsoil)
global.thresh=RsquareAdj(hel.rda.fulsoil)$adj.r.squared

##Pitfall inverts by trees
hel.rda.fulsoil = rda(date3[,5:205],date3[,c(263:297)])
anova(hel.rda.fulsoil)
RsquareAdj(hel.rda.fulsoil)
global.thresh=RsquareAdj(hel.rda.fulsoil)$adj.r.squared

##Pitfall inverts by PCNM
colnames(date3)
all.geog.dist=vegdist(date3[,211:212],method="euclid")
all.pcnm1=pcnm(all.geog.dist)
all.pcnmvecs=all.pcnm1$vectors
# If you can get the PCNM library to run, you could do the line below to select only significantly structured PCNMs
#tree.hel.all.pcnm=cbind(date3,all.pcnmvecs[,which(all.pcnm1$Moran_I[,2]<0.05)])
tree.hel.all.pcnm=cbind(date3,all.pcnmvecs)
names(tree.hel.all.pcnm)
# Now run step 1, global analysis
hel.rda.all.fulpcnm=rda(tree.hel.all.pcnm[,5:205], tree.hel.all.pcnm[,299:317])
anova(hel.rda.all.fulpcnm)
RsquareAdj(hel.rda.all.fulpcnm)
global.thresh=RsquareAdj(hel.rda.all.fulpcnm)$adj.r.squared

#forward selection for our PCNM variables
hel.rda.all.pcnm.none=rda(tree.hel.all.pcnm[,5:205]~1)
hel.rda.all.fulpcnm=rda(tree.hel.all.pcnm[,5:205], tree.hel.all.pcnm[,299:317])

hel.rda.all.pcnm.full=rda(tree.hel.all.pcnm[,5:205]~tree.hel.all.pcnm$PCNM1+tree.hel.all.pcnm$PCNM2+tree.hel.all.pcnm$PCNM3+tree.hel.all.pcnm$PCNM4+tree.hel.all.pcnm$PCNM5+tree.hel.all.pcnm$PCNM6+tree.hel.all.pcnm$PCNM7+tree.hel.all.pcnm$PCNM8+tree.hel.all.pcnm$PCNM9+tree.hel.all.pcnm$PCNM10+tree.hel.all.pcnm$PCNM11+tree.hel.all.pcnm$PCNM12+tree.hel.all.pcnm$PCNM13+tree.hel.all.pcnm$PCNM14+tree.hel.all.pcnm$PCNM15+tree.hel.all.pcnm$PCNM16+tree.hel.all.pcnm$PCNM17+tree.hel.all.pcnm$PCNM18+tree.hel.all.pcnm$PCNM19)

tree.sel=ordiR2step(hel.rda.all.pcnm.none,scope=formula(hel.rda.all.pcnm.full),Pin=0.05,R2scope=TRUE)
tree.sel

##Just the variables forward selected
hel.rda.all.fulpcnm=rda(tree.hel.all.pcnm[,5:205], tree.hel.all.pcnm[,c(305,310:311,314,301:302)])
anova(hel.rda.all.fulpcnm)
RsquareAdj(hel.rda.all.fulpcnm)
global.thresh=RsquareAdj(hel.rda.all.fulpcnm)$adj.r.squared

## Variance partitioning
varpart(tree.hel.all.pcnm[,5:205], tree.hel.all.pcnm[,c(252,238)], tree.hel.all.pcnm[,c(255,276,267,256,262,257,289)])
## Check to see if it's significant when PCNM and soil come first.
hel.rda.all.partpcnm=rda(tree.hel.all.pcnm[,5:205], tree.hel.all.pcnm[,c(255,276,267,256,262,257,289)], tree.hel.all.pcnm[,c(252,238)])
anova(hel.rda.all.partpcnm)
# Yes.
hel.rda.all.partsoil=rda(tree.hel.all.pcnm[,5:205], tree.hel.all.pcnm[,c(252,238)], tree.hel.all.pcnm[,c(255,276,267,256,262,257,289)])
anova(hel.rda.all.partsoil)
# Yes.

##INVERTS BY ECOSYSTEM
hel.rda.fulsoil = rda(date3[,5:205]~date3$TerrType)
anova(hel.rda.fulsoil)
RsquareAdj(hel.rda.fulsoil)
global.thresh=RsquareAdj(hel.rda.fulsoil)$adj.r.squared


####CORE PLOTS####
date3=date3.2[date3.2$EP.x=="Core",]
##rda by soil
hel.rda.fulsoil = rda(date3[,5:205], date3[,229:253])
anova(hel.rda.fulsoil)
RsquareAdj(hel.rda.fulsoil)
global.thresh=RsquareAdj(hel.rda.fulsoil)$adj.r.squared

###Pitter patter, let's get atter. Let's do that sweet sweet forward selection
##Forward selection
hel.rda.fulsoil.none = rda(date3[,5:205]~1)
hel.rda.fulsoil = rda(date3[,5:205], date3[,229:253])

hel.rda.fulsoil.full=rda(date3[,5:205]~date3$Ptot_long+date3$Po_long+date3$pH_long+date3$moist_long+date3$ps1_long+date3$ps2_long+date3$percc_long+date3$cton_long+date3$Ptot_nug+date3$Po_nug+date3$pH_nug+date3$moist_nug+date3$ps1_nug+date3$ps2_nug+date3$percc_nug+date3$pomc_nug+date3$cton_nug+date3$Ptot_short+date3$Po_short+date3$pH_short+date3$moist_short+date3$ps1_short+date3$percc_short+date3$pomc_short+date3$cton_short)

tree.sel=ordiR2step(hel.rda.fulsoil.none,scope=formula(hel.rda.fulsoil.full),Pin=0.05,R2scope=TRUE)
tree.sel

##Just the variables forward selected
hel.rda.fulsoil = rda(date3[,5:205], date3[,c(249,238:239,241)])
anova(hel.rda.fulsoil)
RsquareAdj(hel.rda.fulsoil)
global.thresh=RsquareAdj(hel.rda.fulsoil)$adj.r.squared

##Pitfall inverts by trees
hel.rda.fulsoil = rda(date3[,5:205],date3[,c(263:297)])
anova(hel.rda.fulsoil)
RsquareAdj(hel.rda.fulsoil)
global.thresh=RsquareAdj(hel.rda.fulsoil)$adj.r.squared

##Pitfall inverts by PCNM
colnames(date3)
all.geog.dist=vegdist(date3[,211:212],method="euclid")
all.pcnm1=pcnm(all.geog.dist)
all.pcnmvecs=all.pcnm1$vectors
# If you can get the PCNM library to run, you could do the line below to select only significantly structured PCNMs
#tree.hel.all.pcnm=cbind(date3,all.pcnmvecs[,which(all.pcnm1$Moran_I[,2]<0.05)])
tree.hel.all.pcnm=cbind(date3,all.pcnmvecs)
names(tree.hel.all.pcnm)
# Now run step 1, global analysis
hel.rda.all.fulpcnm=rda(tree.hel.all.pcnm[,5:205], tree.hel.all.pcnm[,299:308])
anova(hel.rda.all.fulpcnm)
RsquareAdj(hel.rda.all.fulpcnm)
global.thresh=RsquareAdj(hel.rda.all.fulpcnm)$adj.r.squared

## Variance partitioning not needed because there's no pcnm effect.

##INVERTS BY ECOSYSTEM
hel.rda.fulsoil = rda(date3[,5:205]~date3$TerrType)
anova(hel.rda.fulsoil)
RsquareAdj(hel.rda.fulsoil)
global.thresh=RsquareAdj(hel.rda.fulsoil)$adj.r.squared

####CORE+EDGE####
date3=date3.2[date3.2$EP.x!="Trans",]
##rda by soil
hel.rda.fulsoil = rda(date3[,5:205], date3[,229:253])
anova(hel.rda.fulsoil)
RsquareAdj(hel.rda.fulsoil)
global.thresh=RsquareAdj(hel.rda.fulsoil)$adj.r.squared

###Pitter patter, let's get atter. Let's do that sweet sweet forward selection
##Forward selection
hel.rda.fulsoil.none = rda(date3[,5:205]~1)
hel.rda.fulsoil = rda(date3[,5:205], date3[,229:253])

hel.rda.fulsoil.full=rda(date3[,5:205]~date3$Ptot_long+date3$Po_long+date3$pH_long+date3$moist_long+date3$ps1_long+date3$ps2_long+date3$percc_long+date3$cton_long+date3$Ptot_nug+date3$Po_nug+date3$pH_nug+date3$moist_nug+date3$ps1_nug+date3$ps2_nug+date3$percc_nug+date3$pomc_nug+date3$cton_nug+date3$Ptot_short+date3$Po_short+date3$pH_short+date3$moist_short+date3$ps1_short+date3$percc_short+date3$pomc_short+date3$cton_short)

tree.sel=ordiR2step(hel.rda.fulsoil.none,scope=formula(hel.rda.fulsoil.full),Pin=0.05,R2scope=TRUE)
tree.sel

##Just the variables forward selected
hel.rda.fulsoil = rda(date3[,5:205], date3[,c(249,252,238)])
anova(hel.rda.fulsoil)
RsquareAdj(hel.rda.fulsoil)
global.thresh=RsquareAdj(hel.rda.fulsoil)$adj.r.squared

##Pitfall inverts by trees
hel.rda.fulsoil = rda(date3[,5:205],date3[,c(263:297)])
anova(hel.rda.fulsoil)
RsquareAdj(hel.rda.fulsoil)
global.thresh=RsquareAdj(hel.rda.fulsoil)$adj.r.squared

##Pitfall inverts by PCNM
colnames(date3)
all.geog.dist=vegdist(date3[,211:212],method="euclid")
all.pcnm1=pcnm(all.geog.dist)
all.pcnmvecs=all.pcnm1$vectors
# If you can get the PCNM library to run, you could do the line below to select only significantly structured PCNMs
#tree.hel.all.pcnm=cbind(date3,all.pcnmvecs[,which(all.pcnm1$Moran_I[,2]<0.05)])
tree.hel.all.pcnm=cbind(date3,all.pcnmvecs)
names(tree.hel.all.pcnm)
# Now run step 1, global analysis
hel.rda.all.fulpcnm=rda(tree.hel.all.pcnm[,5:205], tree.hel.all.pcnm[,299:316])
anova(hel.rda.all.fulpcnm)
RsquareAdj(hel.rda.all.fulpcnm)
global.thresh=RsquareAdj(hel.rda.all.fulpcnm)$adj.r.squared

## Variance partitioning not needed because no pcnm effect.

##INVERTS BY ECOSYSTEM
hel.rda.fulsoil = rda(date3[,5:205]~date3$TerrType)
anova(hel.rda.fulsoil)
RsquareAdj(hel.rda.fulsoil)
global.thresh=RsquareAdj(hel.rda.fulsoil)$adj.r.squared
```
```{r RDA Date 4}
#remove NAs.
date4=na.omit(date4)
#save a back-up for later, just in case.
date4.2=date4
##rda by soil
hel.rda.fulsoil = rda(date4[,5:205], date4[,229:253])
anova(hel.rda.fulsoil)
RsquareAdj(hel.rda.fulsoil)
global.thresh=RsquareAdj(hel.rda.fulsoil)$adj.r.squared

##Pitfall inverts by trees
hel.rda.fulsoil = rda(date4[,5:205],date4[,c(263:297)])
anova(hel.rda.fulsoil)
RsquareAdj(hel.rda.fulsoil)
global.thresh=RsquareAdj(hel.rda.fulsoil)$adj.r.squared

##Pitfall inverts by PCNM
colnames(date4)
all.geog.dist=vegdist(date4[,211:212],method="euclid")
all.pcnm1=pcnm(all.geog.dist)
all.pcnmvecs=all.pcnm1$vectors
# If you can get the PCNM library to run, you could do the line below to select only significantly structured PCNMs
#tree.hel.all.pcnm=cbind(date4,all.pcnmvecs[,which(all.pcnm1$Moran_I[,2]<0.05)])
tree.hel.all.pcnm=cbind(date4,all.pcnmvecs)
names(tree.hel.all.pcnm)
# Now run step 1, global analysis
hel.rda.all.fulpcnm=rda(tree.hel.all.pcnm[,5:205], tree.hel.all.pcnm[,299:318])
anova(hel.rda.all.fulpcnm)
RsquareAdj(hel.rda.all.fulpcnm)
global.thresh=RsquareAdj(hel.rda.all.fulpcnm)$adj.r.squared
## No variance partitioning because no soil/pcnm effect

##INVERTS BY ECOSYSTEM
hel.rda.fulsoil = rda(date4[,5:205]~date4$TerrType)
anova(hel.rda.fulsoil)
RsquareAdj(hel.rda.fulsoil)
global.thresh=RsquareAdj(hel.rda.fulsoil)$adj.r.squared

####CORE PLOTS####
date4=date4.2[date4.2$EP.x=="Core",]
##rda by soil
hel.rda.fulsoil = rda(date4[,5:205], date4[,229:253])
anova(hel.rda.fulsoil)
RsquareAdj(hel.rda.fulsoil)
global.thresh=RsquareAdj(hel.rda.fulsoil)$adj.r.squared

##Pitfall inverts by trees
hel.rda.fulsoil = rda(date4[,5:205],date4[,c(263:297)])
anova(hel.rda.fulsoil)
RsquareAdj(hel.rda.fulsoil)
global.thresh=RsquareAdj(hel.rda.fulsoil)$adj.r.squared

##Pitfall inverts by PCNM
colnames(date4)
all.geog.dist=vegdist(date4[,211:212],method="euclid")
all.pcnm1=pcnm(all.geog.dist)
all.pcnmvecs=all.pcnm1$vectors
# If you can get the PCNM library to run, you could do the line below to select only significantly structured PCNMs
#tree.hel.all.pcnm=cbind(date4,all.pcnmvecs[,which(all.pcnm1$Moran_I[,2]<0.05)])
tree.hel.all.pcnm=cbind(date4,all.pcnmvecs)
names(tree.hel.all.pcnm)
# Now run step 1, global analysis
hel.rda.all.fulpcnm=rda(tree.hel.all.pcnm[,5:205], tree.hel.all.pcnm[,299:308])
anova(hel.rda.all.fulpcnm)
RsquareAdj(hel.rda.all.fulpcnm)
global.thresh=RsquareAdj(hel.rda.all.fulpcnm)$adj.r.squared

## No variance partitioning because no soil/pcnm effects

##INVERTS BY ECOSYSTEM
hel.rda.fulsoil = rda(date4[,5:205]~date4$TerrType)
anova(hel.rda.fulsoil)
RsquareAdj(hel.rda.fulsoil)
global.thresh=RsquareAdj(hel.rda.fulsoil)$adj.r.squared

####CORE+EDGE####
date4=date4.2[date4.2$EP.x!="Trans",]
##rda by soil
hel.rda.fulsoil = rda(date4[,5:205], date4[,229:253])
anova(hel.rda.fulsoil)
RsquareAdj(hel.rda.fulsoil)
global.thresh=RsquareAdj(hel.rda.fulsoil)$adj.r.squared

##Pitfall inverts by trees
hel.rda.fulsoil = rda(date4[,5:205],date4[,c(263:297)])
anova(hel.rda.fulsoil)
RsquareAdj(hel.rda.fulsoil)
global.thresh=RsquareAdj(hel.rda.fulsoil)$adj.r.squared

##Pitfall inverts by PCNM
colnames(date4)
all.geog.dist=vegdist(date4[,211:212],method="euclid")
all.pcnm1=pcnm(all.geog.dist)
all.pcnmvecs=all.pcnm1$vectors
# If you can get the PCNM library to run, you could do the line below to select only significantly structured PCNMs
#tree.hel.all.pcnm=cbind(date4,all.pcnmvecs[,which(all.pcnm1$Moran_I[,2]<0.05)])
tree.hel.all.pcnm=cbind(date4,all.pcnmvecs)
names(tree.hel.all.pcnm)
# Now run step 1, global analysis
hel.rda.all.fulpcnm=rda(tree.hel.all.pcnm[,5:205], tree.hel.all.pcnm[,299:317])
anova(hel.rda.all.fulpcnm)
RsquareAdj(hel.rda.all.fulpcnm)
global.thresh=RsquareAdj(hel.rda.all.fulpcnm)$adj.r.squared

## No variance partitioning because no soil/pcnm effects.

##INVERTS BY ECOSYSTEM
hel.rda.fulsoil = rda(date4[,5:205]~date4$TerrType)
anova(hel.rda.fulsoil)
RsquareAdj(hel.rda.fulsoil)
global.thresh=RsquareAdj(hel.rda.fulsoil)$adj.r.squared
```

Decoupling Stats - Order-wide.
```{r Date 1}
#### Aranaea ####
aranaea.d1=date1[,c(1:4,5:25,206:298)]
#remove NAs.
aranaea.d1=na.omit(aranaea.d1)
#save a back-up for later, just in case.
aranaea.d1.2=aranaea.d1
##rda by soil
hel.rda.fulsoil = rda(aranaea.d1[,7:25], aranaea.d1[,49:73])
anova(hel.rda.fulsoil)#AYO
RsquareAdj(hel.rda.fulsoil)
global.thresh=RsquareAdj(hel.rda.fulsoil)$adj.r.squared

##Pitfall inverts by trees
hel.rda.fulsoil = rda(aranaea.d1[,7:25],aranaea.d1[,c(83:117)])
anova(hel.rda.fulsoil)
RsquareAdj(hel.rda.fulsoil)
global.thresh=RsquareAdj(hel.rda.fulsoil)$adj.r.squared

## Forward Selection
hel.rda.fulsoil.none = rda(aranaea.d1[,7:25]~1)
hel.rda.fulsoil = rda(aranaea.d1[,7:25], aranaea.d1[,83:117])

hel.rda.fulsoil.full=rda(aranaea.d1[,7:25]~aranaea.d1$ACERUB+aranaea.d1$ACESAC+aranaea.d1$ACESIL+aranaea.d1$BETALL+aranaea.d1$CARCAR+aranaea.d1$CARCOR+aranaea.d1$CAROVA+aranaea.d1$CARTOM+aranaea.d1$CORFLO+aranaea.d1$CRAPUN+aranaea.d1$FAGAME+aranaea.d1$FRAAME+aranaea.d1$FRANIG+aranaea.d1$HAMVIR+aranaea.d1$LIRTUP+aranaea.d1$MAGACU+aranaea.d1$MALCOR+aranaea.d1$NYSSYL+aranaea.d1$OSTVIR+aranaea.d1$PLAOCC+aranaea.d1$OSTVIR+aranaea.d1$PLAOCC+aranaea.d1$POPDEL+aranaea.d1$POPGRA+aranaea.d1$PRUSER+aranaea.d1$QUEALB+aranaea.d1$QUEBIC+aranaea.d1$QUEPAL+aranaea.d1$QUERUB+aranaea.d1$SALNIG+aranaea.d1$SASALB+aranaea.d1$TILAME+aranaea.d1$TOXVER+aranaea.d1$ULMAME+aranaea.d1$ULMRUB+aranaea.d1$ULMSP+aranaea.d1$VIBLEN)

tree.sel=ordiR2step(hel.rda.fulsoil.none,scope=formula(hel.rda.fulsoil.full),Pin=0.05,R2scope=TRUE)
tree.sel

##Just the variables forward selected
hel.rda.fulsoil = rda(aranaea.d1[,7:25], aranaea.d1[,c(239,248)])
anova(hel.rda.fulsoil)
RsquareAdj(hel.rda.fulsoil)
global.thresh=RsquareAdj(hel.rda.fulsoil)$adj.r.squared

##Pitfall inverts by PCNM
colnames(aranaea.d1)
all.geog.dist=vegdist(aranaea.d1[,31:32],method="euclid")
all.pcnm1=pcnm(all.geog.dist)
all.pcnmvecs=all.pcnm1$vectors
# If you can get the PCNM library to run, you could do the line below to select only significantly structured PCNMs
#tree.hel.all.pcnm=cbind(aranaea.d1,all.pcnmvecs[,which(all.pcnm1$Moran_I[,2]<0.05)])
tree.hel.all.pcnm=cbind(aranaea.d1,all.pcnmvecs)
names(tree.hel.all.pcnm)
# Now run step 1, global analysis
hel.rda.all.fulpcnm=rda(tree.hel.all.pcnm[,7:25], tree.hel.all.pcnm[,119:134])
anova(hel.rda.all.fulpcnm)
RsquareAdj(hel.rda.all.fulpcnm)
global.thresh=RsquareAdj(hel.rda.all.fulpcnm)$adj.r.squared

## Forward Selection
hel.rda.fulsoil.none = rda(tree.hel.all.pcnm[,7:25]~1)
.hel.rda.fulsoil = rda(tree.hel.all.pcnm[,7:25], tree.hel.all.pcnm[,119:134])

hel.rda.fulsoil.full=rda(tree.hel.all.pcnm[,7:25]~tree.hel.all.pcnm$PCNM1+tree.hel.all.pcnm$PCNM2+tree.hel.all.pcnm$PCNM3+tree.hel.all.pcnm$PCNM4+tree.hel.all.pcnm$PCNM5+tree.hel.all.pcnm$PCNM6+tree.hel.all.pcnm$PCNM7+tree.hel.all.pcnm$PCNM8+tree.hel.all.pcnm$PCNM9+tree.hel.all.pcnm$PCNM10+tree.hel.all.pcnm$PCNM11+tree.hel.all.pcnm$PCNM12+tree.hel.all.pcnm$PCNM13+tree.hel.all.pcnm$PCNM14+tree.hel.all.pcnm$PCNM15+tree.hel.all.pcnm$PCNM16)

tree.sel=ordiR2step(hel.rda.fulsoil.none,scope=formula(hel.rda.fulsoil.full),Pin=0.05,R2scope=TRUE)
tree.sel

##Just the variables forward selected
#hel.rda.fulsoil = rda(tree.hel.all.pcnm[,7:25], tree.hel.all.pcnm[,c(239,248)])
#anova(hel.rda.fulsoil)
#RsquareAdj(hel.rda.fulsoil)
#global.thresh=RsquareAdj(hel.rda.fulsoil)$adj.r.squared

##INVERTS BY ECOSYSTEM
hel.rda.fulsoil = rda(aranaea.d1[,7:25]~aranaea.d1$TerrType)
anova(hel.rda.fulsoil)
RsquareAdj(hel.rda.fulsoil)
global.thresh=RsquareAdj(hel.rda.fulsoil)$adj.r.squared


####CORE PLOTS####
aranaea.d1=aranaea.d1.2[aranaea.d1.2$EP.x=="Core",]
##rda by soil
hel.rda.fulsoil = rda(aranaea.d1[,7:25], aranaea.d1[,49:73])
anova(hel.rda.fulsoil)
RsquareAdj(hel.rda.fulsoil)
global.thresh=RsquareAdj(hel.rda.fulsoil)$adj.r.squared

##Pitfall inverts by trees
hel.rda.fulsoil = rda(aranaea.d1[,7:25],aranaea.d1[,c(83:117)])
anova(hel.rda.fulsoil)
RsquareAdj(hel.rda.fulsoil)
global.thresh=RsquareAdj(hel.rda.fulsoil)$adj.r.squared

##Pitfall inverts by PCNM
colnames(aranaea.d1)
all.geog.dist=vegdist(aranaea.d1[,31:32],method="euclid")
all.pcnm1=pcnm(all.geog.dist)
all.pcnmvecs=all.pcnm1$vectors
# If you can get the PCNM library to run, you could do the line below to select only significantly structured PCNMs
#tree.hel.all.pcnm=cbind(aranaea.d1,all.pcnmvecs[,which(all.pcnm1$Moran_I[,2]<0.05)])
tree.hel.all.pcnm=cbind(aranaea.d1,all.pcnmvecs)
names(tree.hel.all.pcnm)
# Now run step 1, global analysis
hel.rda.all.fulpcnm=rda(tree.hel.all.pcnm[,7:25], tree.hel.all.pcnm[,119:126])
anova(hel.rda.all.fulpcnm)
RsquareAdj(hel.rda.all.fulpcnm)
global.thresh=RsquareAdj(hel.rda.all.fulpcnm)$adj.r.squared

## no variance partitioning needed because no significance/soil effect.

##INVERTS BY ECOSYSTEM
hel.rda.fulsoil = rda(aranaea.d1[,7:25]~aranaea.d1$TerrType)
anova(hel.rda.fulsoil)
RsquareAdj(hel.rda.fulsoil)
global.thresh=RsquareAdj(hel.rda.fulsoil)$adj.r.squared

####CORE+EDGE####
aranaea.d1=aranaea.d1.2[aranaea.d1.2$EP.x!="Trans",]
##rda by soil
hel.rda.fulsoil = rda(aranaea.d1[,7:25], aranaea.d1[,49:73])
anova(hel.rda.fulsoil)
RsquareAdj(hel.rda.fulsoil)
global.thresh=RsquareAdj(hel.rda.fulsoil)$adj.r.squared

##Pitfall inverts by trees
hel.rda.fulsoil = rda(aranaea.d1[,7:25],aranaea.d1[,c(83:117)])
anova(hel.rda.fulsoil)
RsquareAdj(hel.rda.fulsoil)
global.thresh=RsquareAdj(hel.rda.fulsoil)$adj.r.squared

##Pitfall inverts by PCNM
colnames(aranaea.d1)
all.geog.dist=vegdist(aranaea.d1[,31:32],method="euclid")
all.pcnm1=pcnm(all.geog.dist)
all.pcnmvecs=all.pcnm1$vectors
# If you can get the PCNM library to run, you could do the line below to select only significantly structured PCNMs
#tree.hel.all.pcnm=cbind(aranaea.d1,all.pcnmvecs[,which(all.pcnm1$Moran_I[,2]<0.05)])
tree.hel.all.pcnm=cbind(aranaea.d1,all.pcnmvecs)
names(tree.hel.all.pcnm)
# Now run step 1, global analysis
hel.rda.all.fulpcnm=rda(tree.hel.all.pcnm[,7:25], tree.hel.all.pcnm[,119:134])
anova(hel.rda.all.fulpcnm)
RsquareAdj(hel.rda.all.fulpcnm)
global.thresh=RsquareAdj(hel.rda.all.fulpcnm)$adj.r.squared
## Variance partitioning - Not needed because there's no pcnm effect

##INVERTS BY ECOSYSTEM
hel.rda.fulsoil = rda(aranaea.d1[,7:25]~aranaea.d1$TerrType)
anova(hel.rda.fulsoil)
RsquareAdj(hel.rda.fulsoil)
global.thresh=RsquareAdj(hel.rda.fulsoil)$adj.r.squared

#### Coleoptera ####

#### Clitellata ####

#### Chilopoda ####

#### Diplopoda ####

#### Diptera ####

#### Gastropoda ####

#### Hemiptera ####

#### Hymenoptera ####

#### Isopoda ####

#### Orthoptera ####

#### Colembola ####
```



```{r Diversity}
#Gamma diversity between ecosystems
rownames(date1)=date1[,1]
dim(date1)
Hdate1=diversity(date1[1:89,5:205])
raredate1=rarefy(date1[,5:205], 2)-1
specno=specnumber(date1[5:205], MARGIN=1)

botrich=lme(specno~as.factor(TerrType)*Date+Plot,random=~1, data=pitfall)
summary(botrich)
TukeyHSD(botrich)
shapiro.test(specscno)

#Alpha
alpha1=fisher.alpha(date1[,5:205])
alpha2=fisher.alpha(date2[,5:205])
alpha3=fisher.alpha(date3[,5:205])
alpha4=fisher.alpha(date4[,5:205])
boxplot(alpha1)
plot(alpha2)
plot(alpha3)
plot(alpha4)


#Gamma
gammadiv=with(date1, tapply(specnumber(date1[,5:205]),TerrType))
plot(gammadiv)
gamma2=with(date2, tapply(specnumber(date2[,5:205]),TerrType))
gamma3=with(date3, tapply(specnumber(date3[,5:205]),TerrType))
gamma4=with(date4, tapply(specnumber(date4[,5:205]),TerrType))
plot(gammadiv,gamma2,gamma3,gamma4)
#Beta
alpha1 <- with(date1, tapply(specnumber(date1[,5:205]), TerrType, mean))
alpha2 <- with(date2, tapply(specnumber(date2[,5:205]), TerrType, mean))
alpha3 <- with(date3, tapply(specnumber(date3[,5:205]), TerrType, mean))
alpha4 <- with(date4, tapply(specnumber(date4[,5:205]), TerrType, mean))
beta1=gammadiv/alpha1-1
beta2=gamma2/alpha2-1
beta3=gamma3/alpha3-1
beta4=gamma4/alpha4-1

boxplot(alpha1,alpha2,alpha3,alpha4, xlab="Date", ylab="Species Richness")
mtext(side=1,at=1,"26 Sept 2015",las=2,line=1, srt=45)
mtext(side=1,at=2,"24 May 2016",las=2,line=1)
mtext(side=1,at=3,"28 July 2018",las=2,line=1)
mtext(side=1,at=4,"15 Oct 2016",las=2,line=1)


##Real stats or something
colnames(date1)
dim(date1)
rownames(date1)=date1[,1]
Hdate1=diversity(date1[5:205], index="shannon")
rownames(date2)=date2[,1]
Hdate2=diversity(date2[5:205], index="shannon")
rownames(date3)=date3[,1]
Hdate3=diversity(date3[5:205], index="shannon")
rownames(date4)=date4[,1]
Hdate4=diversity(date4[5:205], index="shannon")
boxplot(Hdate1, Hdate2, Hdate3, Hdate4, xlab="Date", ylab="Shannon's Index")
mtext(side=1,at=1,"26 Sept 2015",las=2,line=1, srt=45)
mtext(side=1,at=2,"24 May 2016",las=2,line=1)
mtext(side=1,at=3,"28 July 2018",las=2,line=1)
mtext(side=1,at=4,"15 Oct 2016",las=2,line=1)


#shannon's diversity by ecosystem type
bot=pitfall[pitfall$TerrType=="B",]
rownames(bot)=bot[,1]
b1=bot[bot$Date=="9.26.15",]
b2=bot[bot$Date=="5.24.16",]
b3=bot[bot$Date=="7.28.16",]
b4=bot[bot$Date=="10.15.16",]
dim(bot)
Hbot=diversity(bot[5:205], index="shannon")
hb1=diversity(b1[5:205], index="shannon")
hb2=diversity(b2[5:205], index="shannon")
hb3=diversity(b3[5:205], index="shannon")
hb4=diversity(b4[5:205], index="shannon")
boxplot(Hbot,hb1, hb2, hb3, hb4, xlab="bottomland diversity", ylab="shannons diversity", ylim=c(1,3))
mtext(side=1,at=1,"All Dates",las=2,line=1, srt=45)
mtext(side=1,at=2,"26 Sept 2015",las=2,line=1, srt=45)
mtext(side=1,at=3,"24 May 2016",las=2,line=1)
mtext(side=1,at=4,"28 July 2018",las=2,line=1)
mtext(side=1,at=5,"15 Oct 2016",las=2,line=1)


srb1=specnumber(b1[5:205], MARGIN=1)
srb2=specnumber(b2[5:205], MARGIN=1)
srb3=specnumber(b3[5:205], MARGIN=1)
srb4=specnumber(b4[5:205], MARGIN=1)
boxplot(srb1,srb2,srb3,srb4, xlab="bottomland richness", ylab="species richness", ylim=c(0,40))
mtext(side=1,at=1,"26 Sept 2015",las=2,line=1, srt=45)
mtext(side=1,at=2,"24 May 2016",las=2,line=1)
mtext(side=1,at=3,"28 July 2016",las=2,line=1)
mtext(side=1,at=4,"15 Oct 2016",las=2,line=1)


rip=pitfall[pitfall$TerrType=="R",]
r1=rip[rip$Date=="9.26.15",]
r2=rip[rip$Date=="5.24.16",]
r3=rip[rip$Date=="7.28.16",]
r4=rip[rip$Date=="10.15.16",]
Hrip=diversity(rip[5:205], index="shannon")
hr1=diversity(r1[5:205], index="shannon")
hr2=diversity(r2[5:205], index="shannon")
hr3=diversity(r3[5:205], index="shannon")
hr4=diversity(r4[5:205], index="shannon")
boxplot(Hrip, hr1, hr2, hr3, hr4, xlab="riparian diversity", ylab="shannons diversity",ylim=c(1,3))
mtext(side=1,at=1,"All Dates",las=2,line=1, srt=45)
mtext(side=1,at=2,"26 Sept 2015",las=2,line=1, srt=45)
mtext(side=1,at=3,"24 May 2016",las=2,line=1)
mtext(side=1,at=4,"28 July 2018",las=2,line=1)
mtext(side=1,at=5,"15 Oct 2016",las=2,line=1)


srr1=specnumber(r1[5:205], MARGIN=1)
srr2=specnumber(r2[5:205], MARGIN=1)
srr3=specnumber(r3[5:205], MARGIN=1)
srr4=specnumber(r4[5:205], MARGIN=1)
boxplot(srr1,srr2,srr3,srr4, xlab="riparian richness", ylab="species richness", ylim=c(0,40))
mtext(side=1,at=1,"26 Sept 2015",las=2,line=1, srt=45)
mtext(side=1,at=2,"24 May 2016",las=2,line=1)
mtext(side=1,at=3,"28 July 2018",las=2,line=1)
mtext(side=1,at=4,"15 Oct 2016",las=2,line=1)


upl=pitfall[pitfall$TerrType=="U",]
u1=upl[upl$Date=="9.26.15",]
u2=upl[upl$Date=="5.24.16",]
u3=upl[upl$Date=="7.28.16",]
u4=upl[upl$Date=="10.15.16",]
Hupl=diversity(upl[5:205], index="shannon")
hu1=diversity(u1[5:205], index="shannon")
hu2=diversity(u2[5:205], index="shannon")
hu3=diversity(u3[5:205], index="shannon")
hu4=diversity(u4[5:205], index="shannon")
boxplot(Hupl,hu1, hu2, hu3, hu4, xlab="upland diversity", ylab="shannons diversity", ylim=c(1,3))
mtext(side=1,at=1,"All Dates",las=2,line=1, srt=45)
mtext(side=1,at=2,"26 Sept 2015",las=2,line=1, srt=45)
mtext(side=1,at=3,"24 May 2016",las=2,line=1)
mtext(side=1,at=4,"28 July 2018",las=2,line=1)
mtext(side=1,at=5,"15 Oct 2016",las=2,line=1)


sru1=specnumber(u1[5:205], MARGIN=1)
sru2=specnumber(u2[5:205], MARGIN=1)
sru3=specnumber(u3[5:205], MARGIN=1)
sru4=specnumber(u4[5:205], MARGIN=1)
boxplot(sru1,sru2,sru3,sru4, xlab="upland richness", ylab="species richness", ylim=c(0,40))
mtext(side=1,at=1,"26 Sept 2015",las=2,line=1, srt=45)
mtext(side=1,at=2,"24 May 2016",las=2,line=1)
mtext(side=1,at=3,"28 July 2018",las=2,line=1)
mtext(side=1,at=4,"15 Oct 2016",las=2,line=1)


dis=pitfall[pitfall$TerrType=="D",]
rownames(dis)=dis[,1]
Hdis=diversity(dis[5:205], index="shannon")

boxplot(Hbot, Hrip, Hupl, Hdis, xlab="Ecosystem", ylab="Shannon's Diversity")
mtext(side=1,at=1,"Bottomland",las=2,line=1, srt=45)
mtext(side=1,at=2,"Riparian",las=2,line=1)
mtext(side=1,at=3,"Upland",las=2,line=1)
mtext(side=1,at=4,"Disturbed",las=2,line=1)


halp=aov(Hbot~bot$Date+bot$Plot)
summary(halp)
TukeyHSD(halp)
halp=aov(Hrip~rip$Date+rip$Plot)
summary(halp)
halp=aov(Hupl~upl$Date+upl$Plot)
summary(halp)
halp=aov(Hdis~dis$Date+dis$Plot)
summary(halp)

##Ecotone Diversity and Richness
#uplbot
uplbot=pitfall[pitfall$TerrType=="UB"|pitfall$TerrType=="BU",]
dim(uplbot)
ub1=uplbot[uplbot$Date=="9.26.15",]
ub2=uplbot[uplbot$Date=="5.24.16",]
ub3=uplbot[uplbot$Date=="7.28.16",]
ub4=uplbot[uplbot$Date=="10.15.16",]

ubdall=diversity(uplbot[5:205], index="shannon")
ubd1=diversity(ub1[5:205], index="shannon")
ubd2=diversity(ub2[5:205], index="shannon")
ubd3=diversity(ub3[5:205], index="shannon")
ubd4=diversity(ub4[5:205], index="shannon")
boxplot(ubdall, ubd1, ubd2, ubd3, ubd4, xlab="ub diversity", ylab="shannons diversity", ylim=c(1,3))
mtext(side=1,at=1,"All Dates",las=2,line=1, srt=45)
mtext(side=1,at=2,"26 Sept 2015",las=2,line=1, srt=45)
mtext(side=1,at=3,"24 May 2016",las=2,line=1)
mtext(side=1,at=4,"28 July 2018",las=2,line=1)
mtext(side=1,at=5,"15 Oct 2016",las=2,line=1)

ubr1=specnumber(ub1[5:205], MARGIN=1)
ubr2=specnumber(ub2[5:205], MARGIN=1)
ubr3=specnumber(ub3[5:205], MARGIN=1)
ubr4=specnumber(ub4[5:205], MARGIN=1)
boxplot(ubr1,ubr2,ubr3,ubr4, xlab="UB spp richness", ylab="species richness", ylim=c(0,40))
mtext(side=1,at=1,"26 Sept 2015",las=2,line=1, srt=45)
mtext(side=1,at=2,"24 May 2016",las=2,line=1)
mtext(side=1,at=3,"28 July 2018",las=2,line=1)
mtext(side=1,at=4,"15 Oct 2016",las=2,line=1)

#ripbot
ripbot=pitfall[pitfall$TerrType=="RB"|pitfall$TerrType=="BR",]
dim(ripbot)
rb1=ripbot[ripbot$Date=="9.26.15",]
rb2=ripbot[ripbot$Date=="5.24.16",]
rb3=ripbot[ripbot$Date=="7.28.16",]
rb4=ripbot[ripbot$Date=="10.15.16",]

rbdall=diversity(ripbot[5:205], index="shannon")
rbd1=diversity(rb1[5:205], index="shannon")
rbd2=diversity(rb2[5:205], index="shannon")
rbd3=diversity(rb3[5:205], index="shannon")
rbd4=diversity(rb4[5:205], index="shannon")
boxplot(rbdall, rbd1, rbd2, rbd3, rbd4, xlab="RB diversity", ylab="shannons diversity", ylim=c(1,3))
mtext(side=1,at=1,"All Dates",las=2,line=1, srt=45)
mtext(side=1,at=2,"26 Sept 2015",las=2,line=1, srt=45)
mtext(side=1,at=3,"24 May 2016",las=2,line=1)
mtext(side=1,at=4,"28 July 2018",las=2,line=1)
mtext(side=1,at=5,"15 Oct 2016",las=2,line=1)

rbr1=specnumber(rb1[5:205], MARGIN=1)
rbr2=specnumber(rb2[5:205], MARGIN=1)
rbr3=specnumber(rb3[5:205], MARGIN=1)
rbr4=specnumber(rb4[5:205], MARGIN=1)
boxplot(rbr1,rbr2,rbr3,rbr4, xlab="RB spp richness", ylab="species richness", ylim=c(0,40))
mtext(side=1,at=1,"26 Sept 2015",las=2,line=1, srt=45)
mtext(side=1,at=2,"24 May 2016",las=2,line=1)
mtext(side=1,at=3,"28 July 2018",las=2,line=1)
mtext(side=1,at=4,"15 Oct 2016",las=2,line=1)

#uplrip
uplrip=pitfall[pitfall$TerrType=="UR"|pitfall$TerrType=="RU",]
dim(uplrip)
ur1=uplrip[uplrip$Date=="9.26.15",]
ur2=uplrip[uplrip$Date=="5.24.16",]
ur3=uplrip[uplrip$Date=="7.28.16",]
ur4=uplrip[uplrip$Date=="10.15.16",]

urdall=diversity(uplrip[5:205], index="shannon")
urd1=diversity(ur1[5:205], index="shannon")
urd2=diversity(ur2[5:205], index="shannon")
urd3=diversity(ur3[5:205], index="shannon")
urd4=diversity(ur4[5:205], index="shannon")
boxplot(urdall,urd1, urd2, urd3, urd4, xlab="ur diversity", ylab="shannons diversity", ylim=c(1,3))
mtext(side=1,at=1,"All Dates",las=2,line=1, srt=45)
mtext(side=1,at=2,"26 Sept 2015",las=2,line=1, srt=45)
mtext(side=1,at=3,"24 May 2016",las=2,line=1)
mtext(side=1,at=4,"28 July 2018",las=2,line=1)
mtext(side=1,at=5,"15 Oct 2016",las=2,line=1)


urr1=specnumber(ur1[5:205], MARGIN=1)
urr2=specnumber(ur2[5:205], MARGIN=1)
urr3=specnumber(ur3[5:205], MARGIN=1)
urr4=specnumber(ur4[5:205], MARGIN=1)
srripupl=boxplot(urr1, urr2, urr3, urr4, xlab="ur spp richness", ylab="species richness", ylim=c(0,40))
mtext(side=1,at=1,"26 Sept 2015",las=2,line=1, srt=45)
mtext(side=1,at=2,"24 May 2016",las=2,line=1)
mtext(side=1,at=3,"28 July 2018",las=2,line=1)
mtext(side=1,at=4,"15 Oct 2016",las=2,line=1)

boxplot(hu4, urd4, hr4, xlab="Ecosystem", ylab="Shannons diversity")
mtext(side=1,at=1,"U",las=2,line=1, srt=45)
mtext(side=1,at=2,"UR",las=2,line=1)
mtext(side=1,at=3,"R",las=2,line=1)

boxplot(sru4, urr4, srr4, xlab="Ecosystem", ylab="species richness")
mtext(side=1,at=1,"U",las=2,line=1, srt=45)
mtext(side=1,at=2,"UR",las=2,line=1)
mtext(side=1,at=3,"R",las=2,line=1)



####GRAHING FOR ESA
boxplot(hr1, hr2, hr3, hr4, ylab="Shannon's Diversity")
title(main = "Riparian")

boxplot(srr1,srr2,srr3,srr4, xlab="Date", ylab="Taxonomic Richness", ylim=c(5,25))
mtext(side=1,at=1,"26 Sept 2015",las=0,line=1, srt=45)
mtext(side=1,at=2,"24 May 2016",las=0,line=1)
mtext(side=1,at=3,"28 July 2018",las=0,line=1)
mtext(side=1,at=4,"15 Oct 2016",las=0,line=1)

boxplot(urd1, urd2, urd3, urd4, xlab="") #Ecotone Diversity
title(main="Riparian-Upland")


srripupl=boxplot(urr1, urr2, urr3, urr4, xlab="Date") #SR RipUpl
mtext(side=1,at=1,"26 Sept 2015",las=0,line=1, srt=45)
mtext(side=1,at=2,"24 May 2016",las=0,line=1)
mtext(side=1,at=3,"28 July 2018",las=0,line=1)
mtext(side=1,at=4,"15 Oct 2016",las=0,line=1)

boxplot(hu1, hu2, hu3, hu4, xlab="") #Upland Diversity
title(main="Upland")

boxplot(sru1,sru2,sru3,sru4, xlab="Date", main="Upland")
mtext(side=1,at=1,"26 Sept 2015",las=0,line=1, srt=45)
mtext(side=1,at=2,"24 May 2016",las=0,line=1)
mtext(side=1,at=3,"28 July 2018",las=0,line=1)
mtext(side=1,at=4,"15 Oct 2016",las=0,line=1)



###
pitfall.core=pitfall[pitfall$EP.x=="Core",]
dim(pitfall.core)
halldates=diversity(pitfall.core[,5:205], index="shannon")
alldates=lme(halldates~TerrType*Date, random = ~ 1|Plot, data=pitfall.core)
anova(alldates)

sralldates=specnumber(pitfall.core[5:205], MARGIN=1)
datesall=lme(sralldates~TerrType*Date, random=~1|Plot, data=pitfall.core)
anova(datesall)

pitfall.edge=pitfall[pitfall$EP.x!="Trans",]
pitfall.edge=pitfall.edge[pitfall.edge$TerrType!="UR",]
dim(pitfall.edge)

halldates1=diversity(pitfall.edge[5:205], index="shannon")
alldates1=lme(halldates1~TerrType*Date, random = ~ 1|Plot, data=pitfall.edge)
anova(alldates1)

sralldates1=specnumber(pitfall.edge[5:205], MARGIN=1)
datesall1=lme(sralldates1~TerrType*Date, random=~1|Plot, data=pitfall.edge)
anova(datesall1)
summary(datesall1)

pitfall.edge$TerrType
colnames(pitfall)
pitfall$TerrType


colnames(pitfall)=pitfall[1,]
lme(Hdate1~TerrType+Plot, data=date1)
```

```{r CCA; H1}
## Date 1
##Let's take out the TerrTypes that we don't test (like things that include D and thus don't have replicates)
date1.cca=date1[date1$TerrType=="B"|date1$TerrType=="RU"|date1$TerrType=="U"|date1$TerrType=="BU"|date1$TerrType=="UR"|date1$TerrType=="T-UR"|date1$TerrType=="UB"|date1$TerrType=="T-UB"|date1$TerrType=="R"|date1$TerrType=="RB"|date1$TerrType=="BR"|date1$TerrType=="T-RB",]

## the CCA
pit.cca.d1=cca(date1.cca[,5:205]~date1.cca$TerrType)
anova(pit.cca.d1)
plot(pit.cca.d1)

## Date 2
date2.cca=date2[date2$TerrType=="B"|date2$TerrType=="RU"|date2$TerrType=="U"|date2$TerrType=="BU"|date2$TerrType=="UR"|date2$TerrType=="T-UR"|date2$TerrType=="UB"|date2$TerrType=="T-UB"|date2$TerrType=="R"|date2$TerrType=="RB"|date2$TerrType=="BR"|date2$TerrType=="T-RB",]

pit.cca.d2=cca(date2.cca[,5:205]~date2.cca$TerrType)
anova(pit.cca.d2)
plot(pit.cca.d2)

## Date 3
date3.cca=date3[date3$TerrType=="B"|date3$TerrType=="RU"|date3$TerrType=="U"|date3$TerrType=="BU"|date3$TerrType=="UR"|date3$TerrType=="T-UR"|date3$TerrType=="UB"|date3$TerrType=="T-UB"|date3$TerrType=="R"|date3$TerrType=="RB"|date3$TerrType=="BR"|date3$TerrType=="T-RB",]
pit.cca.d3=cca(date3.cca[,5:205]~date3.cca$TerrType)
anova(pit.cca.d3)
plot(pit.cca.d3)
scores(pit.cca.d3)

## Date 4
date4.cca=date4[date4$TerrType=="B"|date4$TerrType=="RU"|date4$TerrType=="U"|date4$TerrType=="BU"|date4$TerrType=="UR"|date4$TerrType=="T-UR"|date4$TerrType=="UB"|date4$TerrType=="T-UB"|date4$TerrType=="R"|date4$TerrType=="RB"|date4$TerrType=="BR"|date4$TerrType=="T-RB",]
pit.cca.d4=cca(date4.cca[,5:205]~date4.cca$TerrType)
anova(pit.cca.d4)
plot(pit.cca.d4)
```
```{r NMDS}
##Subset the dataset to remove plots and columns we don't need.
pitfall.data.nmds=pitfall[,1:212]
pitfall.data.nmds=pitfall.data.nmds[pitfall.data.nmds$TerrType=="B"|pitfall.data.nmds$TerrType=="R"|pitfall.data.nmds$TerrType=="U"|pitfall.data.nmds$TerrType=="BU"|pitfall.data.nmds$TerrType=="UB"|pitfall.data.nmds$TerrType=="RU"|pitfall.data.nmds$TerrType=="UR"|pitfall.data.nmds$TerrType=="BR"|pitfall.data.nmds$TerrType=="RB",]
pitfall.groups=c(pitfall$TerrType,pitfall[,5:205])

## Set up distance matrix
pitfall.rel.abun=decostand(pitfall.data.nmds[,5:205], method="total",labels=T)
pitfall.distance=vegdist(pitfall.rel.abun, method="bray",labels=T)
pitfall.dist.mat=as.matrix(pitfall.distance, labels= T)

##NMDS
pitfall.nmds=metaMDS(pitfall.dist.mat, 
                     distance="bray", 
                     k=3, 
                     maxit=999, 
                     trymax=500, 
                     wascores=TRUE)
goodness(pitfall.nmds)
stressplot(pitfall.nmds)

##Plot
plot(pitfall.nmds, "sites")
orditorp(pitfall.nmds, "sites")

##Let's jazz up this plot a little bit.
colvec<-c("gray0","red1","cornflowerblue","lightcyan3","tomato3","blueviolet")

plot(pitfall.nmds)
with(pitfall.groups,
     points(pitfall.nmds,
            display="sites",
            col="black",
            bg=colvec[TerrType]))
```